### ISSUE TITLE
i make it but have problem

### ISSUE THREAD

**Issue by wertrigone** [johnwayne087/Telegram-Bot-TextGenWebui#1]
i make install all lib pip install python-telegram-bot==13.15 requests and pip install python-telegram-bot==13.15 
but when i start i have problem:
ilya, [27.04.2024 22:35]
hello!

Guru, [27.04.2024 22:35]
Sorry, there was an error generating a response.

at console: c:\1>python bot.py
Unexpected status code: 404
Response content: b'{"detail":"Not Found"}'

**Comment by johnwayne087** [comment]
I uploaded a new script, test that one out and let me know if it works,
